apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: ristov211151/app:latest
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://db-statefulset.myapp-namespace.svc.cluster.local:5432/kii"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
          ports:
            - containerPort: 8080
